import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { cn, heliosfont } from "@/lib/utils";
import { Inter } from 'next/font/google'
import Footer from "@/components/ui/footer";

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("font-sans", heliosfont.variable, inter.variable)}
      >
        <Navbar/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
