import DashboardSidebar from "@/components/featured/dashboard/components/dashboard-sidebar";
import Footer from "@/components/ui/footer";
import Navbar from "@/components/ui/navbar";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Beranda",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <Navbar/>
            <main>
                {children}
            </main>
            <Footer/>
        </div>
    );
}